services:
  service-pg:
    image: bitnami/postgresql:latest
    container_name: service-pg
    ports:
      - '5433:5432'
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: moneyger
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
