services:
  service-pg:
    image: bitnami/postgresql:latest
    container_name: service-pg
    ports:
      - '5433:5432'
    environment:
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
